# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 04:46
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_batches', '0002_auto_20170214_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='resume',
            field=models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(location='batches/job/resume'), upload_to=''),
        ),
    ]
