# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 05:07
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_batches', '0003_job_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverLetter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('file', models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='batches/job/cover'), upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('file', models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='batches/job/resume'), upload_to='')),
            ],
        ),
        migrations.RenameField(
            model_name='companybatch',
            old_name='job_type',
            new_name='job',
        ),
        migrations.RemoveField(
            model_name='job',
            name='resume',
        ),
        migrations.AddField(
            model_name='companybatch',
            name='cover_letter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company_batches.CoverLetter'),
        ),
        migrations.AddField(
            model_name='companybatch',
            name='resume',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company_batches.Resume'),
        ),
    ]
