# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_batches', '0004_auto_20170214_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companybatch',
            name='job',
        ),
        migrations.RemoveField(
            model_name='coverletter',
            name='name',
        ),
        migrations.RemoveField(
            model_name='job',
            name='desired_salary',
        ),
        migrations.RemoveField(
            model_name='job',
            name='remote_option',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='name',
        ),
        migrations.AddField(
            model_name='company',
            name='job',
            field=models.ManyToManyField(to='company_batches.Job'),
        ),
    ]
